name: Deploy to FTP

# Déclencher le workflow
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Permet de déclencher manuellement

jobs:
  deploy:
    name: Deploy to FTP Server
    runs-on: ubuntu-latest

    steps:
    # Checkout du code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Validation des secrets FTP requis
    - name: Validate FTP secrets
      run: |
        if [ -z "${{ secrets.FTP_HOST }}" ]; then
          echo "❌ Erreur: Le secret FTP_HOST n'est pas configuré"
          echo "📝 Configurez FTP_HOST dans Settings → Secrets and variables → Actions"
          exit 1
        fi
        if [ -z "${{ secrets.FTP_USER }}" ]; then
          echo "❌ Erreur: Le secret FTP_USER n'est pas configuré"
          exit 1
        fi
        if [ -z "${{ secrets.FTP_PASSWORD }}" ]; then
          echo "❌ Erreur: Le secret FTP_PASSWORD n'est pas configuré"
          exit 1
        fi
        echo "✅ Tous les secrets FTP requis sont configurés"

    # Configuration Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    # Installation des dépendances
    - name: Install dependencies
      run: npm ci

    # Build de production
    - name: Build for production
      run: npm run generate:production
      env:
        NUXT_APP_BASE_URL: /txtengage/

    # Vérification du build
    - name: Verify build output
      run: |
        if [ ! -d "./.output/public" ]; then
          echo "❌ Erreur: Le dossier de build ./.output/public n'existe pas"
          echo "📁 Contenu du dossier .output:"
          ls -la ./.output/ || echo "Le dossier .output n'existe pas"
          exit 1
        fi
        echo "✅ Build vérifié - dossier .output/public trouvé"
        echo "📁 Contenu à déployer:"
        ls -la ./.output/public/

    # Déploiement FTP avec action spécialisée
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT || 21 }}
        protocol: ${{ secrets.FTP_SECURE == 'true' && 'ftps' || 'ftp' }}
        local-dir: ./.output/public/
        server-dir: ${{ secrets.FTP_REMOTE_PATH || '/public_html/txtengage/' }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.DS_Store
          **/*.map
        log-level: verbose

    # Alternative: Déploiement FTP avec script custom
    - name: Deploy with custom FTP script
      if: false  # Désactivé par défaut, activez si nécessaire
      run: npm run deploy:ftp
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USER: ${{ secrets.FTP_USER }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_PORT: ${{ secrets.FTP_PORT }}
        FTP_SECURE: ${{ secrets.FTP_SECURE }}
        FTP_REMOTE_PATH: ${{ secrets.FTP_REMOTE_PATH }}

    # Notification de succès
    - name: Notify success
      if: success()
      run: |
        echo "🚀 Déploiement réussi vers le dossier txtengage!"
        echo "🌐 Site accessible à: ${{ secrets.FTP_HOST }}${{ secrets.FTP_REMOTE_PATH || '/txtengage/' }}"

    # Notification d'échec avec aide
    - name: Notify failure
      if: failure()
      run: |
        echo "❌ Échec du déploiement. Vérifiez les logs."
        echo ""
        echo "🔧 Pour résoudre:"
        echo "1. Vérifiez que tous les secrets FTP sont configurés dans GitHub"
        echo "2. Testez vos identifiants FTP manuellement"
        echo "3. Vérifiez que le chemin distant existe sur le serveur"
        echo "4. Consultez les logs détaillés ci-dessus" 